name: CI
on:
  push:
    branches:
      - master

jobs:
  buils:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        poetry-version: [ 1.1.5 ]
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install deps
        run: poetry install -vv
      - name: Build package
        run: poetry run pyinstaller --onefile main.py
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-20.04'
        with:
          name: linux-dist
          path: dist/*
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: macos-dist
          path: dist/*
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: windows-dist
          path: dist/*